spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

api.security.token.secret=${JWT_SECRET:autoflow-chave-secreta-super-segura-e-longa-12345}
api.security.token.expiration-minutes=10

spring.jpa.show-sql=true